### ISSUE TITLE
Can't connect EVE account to REvernus.

### ISSUE THREAD

**Issue by EVEarchitect** [Meigs2/REvernus#2]
When trying to add my character, after signing into EVE I'm getting the error: {"error":"invalid_request","error_description":"The state parameter is required."}

The only clue I see may be in the URL, which seems to be cut off ending in: +esi-corporations.read_starbases.v1+esi-industry.read_corpora

I hope this project works out! Really looking forward to it!

**Comment by Meigs2** [comment]
Hmm. It seems that when the program opens the sign-in URL you need to visit, the browser is cutting off the end of the string and not providing all the information required to sign in. What web browser are you using?

**Comment by Meigs2** [comment]
I'm going to close this issue for now, if the problem persists please let us know!

**Comment by Meigs2** [comment]
Apparently this issue is not localized, so I am reopening this issue. Any help with this would be appreciated!

Currently, it does not seem to be a browser based issue. One user in the discord reported the problem to be occurring in Firefox, however during my testing Authing worked in Firefox just fine.

**Comment by Meigs2** [comment]
It seems we fixed the URL issue by trimming back scopes. That being said, it seems that this may be a .Net Core 3 and Windows 7 Issue.
